title: "bootcamp-programacion-web"
# remote_theme: just-the-docs/just-the-docs
theme: "just-the-docs"
# color_scheme: "dark"
search_enabled: false
logo: "/assets/images/logo.png"
heading_anchors: true
